# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "676e6f6769ea56c7c520e7ba19dd7f55"
name = "adrs-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_products,write_checkouts,write_customers,write_price_rules,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
