api_version = "2025-07"

[[extensions]]
name = "connect-wallet"
type = "theme"
handle = "connect-wallet"
uid = "57f3e737-e281-73a2-9036-c50f69eab5afb14f8b6f"

# 1. This allows you to add it as a block inside the Header
[[blocks]]
name = "Connect Wallet Button"
target = "section"
type = "app"
enabled_on = { templates = ["*"] }

# 2. (Optional) This allows you to add it as a floating widget
[[blocks]]
name = "Wallet Floating Widget"
target = "body"
type = "app_embed"